services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo-data:/data/db

  logistics_service:
    build: ./Logistics-System/Services/Logistics_Service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mongo

  standard_delivery:
    build: ./Logistics-System/Services/Standard_Delivery
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  express_delivery:
    build: ./Logistics-System/Services/Express_Delivery
    ports:
      - "8082:8082"
    depends_on:
      - kafka

  international_delivery:
    build: ./Logistics-System/Services/International_Delivery
    ports:
      - "8083:8083"
    depends_on:
      - kafka

volumes:
  mongo-data:
